/**
 * PREPARE IMAGES
 * ==============
 * Downloads the stock sources, bakes them to greyscale, and writes compressed
 * WebP into public/images. Run it with:
 *
 *     node scripts/prepare-images.mjs
 *
 * ── WHY GREYSCALE IS BAKED IN ───────────────────────────────────────────────
 * PopImage builds its duotone from CSS blend layers over a greyscale source.
 * It CAN greyscale at runtime with a CSS filter, but that filter is the
 * expensive half of the treatment on a mid-range phone. Baking it here means
 * the browser does no filtering at all, and greyscale also compresses far
 * smaller than colour — roughly a third off, for free.
 *
 * Components using these files pass `preGreyscaled` so the runtime filter is
 * skipped.
 *
 * ── PICKING SOURCES ─────────────────────────────────────────────────────────
 * Tight crops and detail shots only, and NO identifiable faces. A clear photo
 * of a real band on a real stage would read as "a past Kool Kalakaars night",
 * which would be a fabricated past event even though the photo is properly
 * licensed. Hands, strings, hardware, silhouettes — nothing that implies a
 * performance that has not happened.
 *
 * To swap in real event photography later: replace the entries below (or just
 * drop files straight into public/images and point site.config.ts at them).
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "public", "images");

/**
 * Every source, with its licence and credit recorded. The Unsplash Licence
 * does not require attribution, but we credit anyway — it costs nothing and
 * it is the decent thing to do.
 */
const SOURCES = [
  {
    slug: "open-mic",
    cdn: "https://images.unsplash.com/photo-1675430428298-ecd1827c18fd",
    page: "https://unsplash.com/photos/a-close-up-of-a-microphone-in-a-dark-room-PMN6wntEQtQ",
    credit: "benjamin lehman",
    licence: "Unsplash Licence",
    subject: "Close crop of a stage microphone in a dark room",
    faces: false,
  },
  {
    slug: "band",
    cdn: "https://images.unsplash.com/photo-1456948927036-ad533e53865c",
    page: "https://unsplash.com/photos/TVgcpjm7jxc",
    credit: "Matija Sundalic",
    licence: "Unsplash Licence",
    subject: "Macro detail of the strings and body of a black electric guitar",
    faces: false,
  },
  {
    slug: "solo-instrumental",
    cdn: "https://images.unsplash.com/photo-1568219656418-15c329312bf1",
    page: "https://unsplash.com/photos/rTikKt6ir5g",
    credit: "Ricky Singh",
    licence: "Unsplash Licence",
    subject: "Hands mid-strike on a tabla",
    faces: false,
  },
];

/** Category cards render in a 4:5 box. 900x1125 covers 2x on both layouts. */
const WIDTH = 900;
const HEIGHT = 1125;

async function run() {
  await mkdir(OUT_DIR, { recursive: true });
  const report = [];

  for (const src of SOURCES) {
    process.stdout.write(`  ${src.slug} … `);

    const url = `${src.cdn}?w=1800&q=90&fm=jpg&fit=crop`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${src.slug}: HTTP ${res.status}`);

    const input = Buffer.from(await res.arrayBuffer());

    const output = await sharp(input)
      .resize(WIDTH, HEIGHT, { fit: "cover", position: "attention" })
      // Baked greyscale + a nudge of contrast, so the duotone blend has a
      // full tonal range to map across.
      .greyscale()
      .linear(1.12, -12)
      .webp({ quality: 82, effort: 6 })
      .toBuffer();

    const file = join(OUT_DIR, `${src.slug}.webp`);
    await writeFile(file, output);

    const kb = (output.length / 1024).toFixed(0);
    console.log(`${kb} KB  (${WIDTH}x${HEIGHT} greyscale webp)`);
    report.push({ ...src, kb, file: `/images/${src.slug}.webp` });
  }

  /* Credits file, regenerated from the manifest so it can never drift. */
  const credits = [
    "# Image credits",
    "",
    "Generated by `scripts/prepare-images.mjs`. Do not edit by hand — edit the",
    "manifest in that script and re-run it.",
    "",
    "All sources are tight detail crops with **no identifiable faces**. This is",
    "deliberate: a recognisable photo of a band on a stage would read as a past",
    "Kool Kalakaars event, and no event has happened yet.",
    "",
    "Every image is processed to greyscale at build time and coloured in the",
    "browser by `PopImage`, so none of it reads as raw stock.",
    "",
    "| File | Subject | Photographer | Licence | Source |",
    "| --- | --- | --- | --- | --- |",
    ...report.map(
      (r) =>
        `| \`${r.file}\` | ${r.subject} | ${r.credit} | ${r.licence} | [page](${r.page}) |`,
    ),
    "",
    "## The Unsplash Licence",
    "",
    "Free for commercial and non-commercial use, no permission needed and no",
    "attribution required. Photographs may not be sold unmodified, and may not",
    "be used to build a competing service. Full terms:",
    "<https://unsplash.com/license>",
    "",
    "We credit the photographers anyway.",
    "",
  ].join("\n");

  await writeFile(join(ROOT, "docs", "IMAGE_CREDITS.md"), credits);
  console.log(`\n  ${report.length} images written to public/images`);
  console.log("  docs/IMAGE_CREDITS.md regenerated\n");
}

run().catch((err) => {
  console.error("\nFAILED:", err.message);
  process.exit(1);
});
